use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RadarSite {
    pub id: &'static str,
    pub name: &'static str,
    pub lat: f64,
    pub lon: f64,
    pub state: &'static str,
}

pub static RADAR_SITES: &[RadarSite] = &[
    RadarSite {
        id: "KABR",
        name: "Aberdeen",
        lat: 45.4558,
        lon: -98.4131,
        state: "SD",
    },
    RadarSite {
        id: "KABX",
        name: "Albuquerque",
        lat: 35.1497,
        lon: -106.824,
        state: "NM",
    },
    RadarSite {
        id: "KAKQ",
        name: "Wakefield",
        lat: 36.9839,
        lon: -77.0075,
        state: "VA",
    },
    RadarSite {
        id: "KAMA",
        name: "Amarillo",
        lat: 35.2333,
        lon: -101.709,
        state: "TX",
    },
    RadarSite {
        id: "KAMX",
        name: "Miami",
        lat: 25.6111,
        lon: -80.4128,
        state: "FL",
    },
    RadarSite {
        id: "KAPX",
        name: "Gaylord",
        lat: 44.9072,
        lon: -84.7197,
        state: "MI",
    },
    RadarSite {
        id: "KARX",
        name: "La Crosse",
        lat: 43.8228,
        lon: -91.1911,
        state: "WI",
    },
    RadarSite {
        id: "KATX",
        name: "Seattle",
        lat: 48.1944,
        lon: -122.496,
        state: "WA",
    },
    RadarSite {
        id: "KBBX",
        name: "Beale AFB",
        lat: 39.4961,
        lon: -121.632,
        state: "CA",
    },
    RadarSite {
        id: "KBGM",
        name: "Binghamton",
        lat: 42.1997,
        lon: -75.985,
        state: "NY",
    },
    RadarSite {
        id: "KBHX",
        name: "Eureka",
        lat: 40.4986,
        lon: -124.292,
        state: "CA",
    },
    RadarSite {
        id: "KBIS",
        name: "Bismarck",
        lat: 46.7708,
        lon: -100.76,
        state: "ND",
    },
    RadarSite {
        id: "KBLX",
        name: "Billings",
        lat: 45.8536,
        lon: -108.607,
        state: "MT",
    },
    RadarSite {
        id: "KBMX",
        name: "Birmingham",
        lat: 33.1722,
        lon: -86.7697,
        state: "AL",
    },
    RadarSite {
        id: "KBOX",
        name: "Boston",
        lat: 41.9558,
        lon: -71.1369,
        state: "MA",
    },
    RadarSite {
        id: "KBRO",
        name: "Brownsville",
        lat: 25.9161,
        lon: -97.4189,
        state: "TX",
    },
    RadarSite {
        id: "KBUF",
        name: "Buffalo",
        lat: 42.9486,
        lon: -78.7369,
        state: "NY",
    },
    RadarSite {
        id: "KBYX",
        name: "Key West",
        lat: 24.5975,
        lon: -81.7031,
        state: "FL",
    },
    RadarSite {
        id: "KCAE",
        name: "Columbia",
        lat: 33.9486,
        lon: -81.1186,
        state: "SC",
    },
    RadarSite {
        id: "KCBW",
        name: "Caribou",
        lat: 46.0392,
        lon: -67.8064,
        state: "ME",
    },
    RadarSite {
        id: "KCBX",
        name: "Boise",
        lat: 43.4908,
        lon: -116.236,
        state: "ID",
    },
    RadarSite {
        id: "KCCX",
        name: "State College",
        lat: 40.9228,
        lon: -78.0039,
        state: "PA",
    },
    RadarSite {
        id: "KCLE",
        name: "Cleveland",
        lat: 41.4131,
        lon: -81.86,
        state: "OH",
    },
    RadarSite {
        id: "KCLX",
        name: "Charleston",
        lat: 32.6556,
        lon: -81.0422,
        state: "SC",
    },
    RadarSite {
        id: "KCRP",
        name: "Corpus Christi",
        lat: 27.7842,
        lon: -97.5111,
        state: "TX",
    },
    RadarSite {
        id: "KCXX",
        name: "Burlington",
        lat: 44.5111,
        lon: -73.1667,
        state: "VT",
    },
    RadarSite {
        id: "KCYS",
        name: "Cheyenne",
        lat: 41.1519,
        lon: -104.806,
        state: "WY",
    },
    RadarSite {
        id: "KDAX",
        name: "Sacramento",
        lat: 38.5011,
        lon: -121.678,
        state: "CA",
    },
    RadarSite {
        id: "KDDC",
        name: "Dodge City",
        lat: 37.7608,
        lon: -99.9689,
        state: "KS",
    },
    RadarSite {
        id: "KDFX",
        name: "Laughlin AFB",
        lat: 29.2725,
        lon: -100.281,
        state: "TX",
    },
    RadarSite {
        id: "KDGX",
        name: "Brandon",
        lat: 32.28,
        lon: -89.9844,
        state: "MS",
    },
    RadarSite {
        id: "KDIX",
        name: "Philadelphia",
        lat: 39.9469,
        lon: -74.4108,
        state: "NJ",
    },
    RadarSite {
        id: "KDLH",
        name: "Duluth",
        lat: 46.8369,
        lon: -92.2097,
        state: "MN",
    },
    RadarSite {
        id: "KDMX",
        name: "Des Moines",
        lat: 41.7311,
        lon: -93.7228,
        state: "IA",
    },
    RadarSite {
        id: "KDOX",
        name: "Dover AFB",
        lat: 38.8256,
        lon: -75.44,
        state: "DE",
    },
    RadarSite {
        id: "KDTX",
        name: "Detroit",
        lat: 42.6997,
        lon: -83.4717,
        state: "MI",
    },
    RadarSite {
        id: "KDVN",
        name: "Davenport",
        lat: 41.6117,
        lon: -90.5808,
        state: "IA",
    },
    RadarSite {
        id: "KDYX",
        name: "Dyess AFB",
        lat: 32.5386,
        lon: -99.2542,
        state: "TX",
    },
    RadarSite {
        id: "KEAX",
        name: "Kansas City",
        lat: 38.8103,
        lon: -94.2644,
        state: "MO",
    },
    RadarSite {
        id: "KEMX",
        name: "Tucson",
        lat: 31.8936,
        lon: -110.63,
        state: "AZ",
    },
    RadarSite {
        id: "KENX",
        name: "Albany",
        lat: 42.5864,
        lon: -74.0639,
        state: "NY",
    },
    RadarSite {
        id: "KEOX",
        name: "Fort Rucker",
        lat: 31.4606,
        lon: -85.4594,
        state: "AL",
    },
    RadarSite {
        id: "KEPZ",
        name: "El Paso",
        lat: 31.8731,
        lon: -106.698,
        state: "TX",
    },
    RadarSite {
        id: "KESX",
        name: "Las Vegas",
        lat: 35.7011,
        lon: -114.892,
        state: "NV",
    },
    RadarSite {
        id: "KEVX",
        name: "NW Florida",
        lat: 30.5644,
        lon: -85.9214,
        state: "FL",
    },
    RadarSite {
        id: "KEWX",
        name: "Austin/San Antonio",
        lat: 29.7039,
        lon: -98.0286,
        state: "TX",
    },
    RadarSite {
        id: "KEYX",
        name: "Edwards AFB",
        lat: 35.0978,
        lon: -117.561,
        state: "CA",
    },
    RadarSite {
        id: "KFCX",
        name: "Roanoke",
        lat: 37.0242,
        lon: -80.2742,
        state: "VA",
    },
    RadarSite {
        id: "KFDR",
        name: "Frederick",
        lat: 34.3622,
        lon: -98.9764,
        state: "OK",
    },
    RadarSite {
        id: "KFDX",
        name: "Cannon AFB",
        lat: 34.6353,
        lon: -103.631,
        state: "NM",
    },
    RadarSite {
        id: "KFFC",
        name: "Atlanta",
        lat: 33.3636,
        lon: -84.5658,
        state: "GA",
    },
    RadarSite {
        id: "KFSD",
        name: "Sioux Falls",
        lat: 43.5878,
        lon: -96.7292,
        state: "SD",
    },
    RadarSite {
        id: "KFSX",
        name: "Flagstaff",
        lat: 34.5744,
        lon: -111.198,
        state: "AZ",
    },
    RadarSite {
        id: "KFTG",
        name: "Denver",
        lat: 39.7867,
        lon: -104.546,
        state: "CO",
    },
    RadarSite {
        id: "KFWS",
        name: "Dallas/Ft Worth",
        lat: 32.5731,
        lon: -97.3028,
        state: "TX",
    },
    RadarSite {
        id: "KGGW",
        name: "Glasgow",
        lat: 48.2064,
        lon: -106.625,
        state: "MT",
    },
    RadarSite {
        id: "KGJX",
        name: "Grand Junction",
        lat: 39.0619,
        lon: -108.214,
        state: "CO",
    },
    RadarSite {
        id: "KGLD",
        name: "Goodland",
        lat: 39.3667,
        lon: -101.7,
        state: "KS",
    },
    RadarSite {
        id: "KGRB",
        name: "Green Bay",
        lat: 44.4986,
        lon: -88.1111,
        state: "WI",
    },
    RadarSite {
        id: "KGRK",
        name: "Central Texas",
        lat: 30.7217,
        lon: -97.3828,
        state: "TX",
    },
    RadarSite {
        id: "KGRR",
        name: "Grand Rapids",
        lat: 42.8939,
        lon: -85.5447,
        state: "MI",
    },
    RadarSite {
        id: "KGSP",
        name: "Greenville",
        lat: 34.8833,
        lon: -82.2200,
        state: "SC",
    },
    RadarSite {
        id: "KGWX",
        name: "Columbus AFB",
        lat: 33.8967,
        lon: -88.3289,
        state: "MS",
    },
    RadarSite {
        id: "KGYX",
        name: "Portland",
        lat: 43.8914,
        lon: -70.2564,
        state: "ME",
    },
    RadarSite {
        id: "KHDX",
        name: "Holloman AFB",
        lat: 33.0769,
        lon: -106.123,
        state: "NM",
    },
    RadarSite {
        id: "KHGX",
        name: "Houston",
        lat: 29.4719,
        lon: -95.0792,
        state: "TX",
    },
    RadarSite {
        id: "KHNX",
        name: "Hanford",
        lat: 36.3142,
        lon: -119.632,
        state: "CA",
    },
    RadarSite {
        id: "KHPX",
        name: "Fort Campbell",
        lat: 36.7369,
        lon: -87.285,
        state: "KY",
    },
    RadarSite {
        id: "KHTX",
        name: "Huntsville",
        lat: 34.9306,
        lon: -86.0833,
        state: "AL",
    },
    RadarSite {
        id: "KICT",
        name: "Wichita",
        lat: 37.6544,
        lon: -97.4428,
        state: "KS",
    },
    RadarSite {
        id: "KICX",
        name: "Cedar City",
        lat: 37.5908,
        lon: -112.862,
        state: "UT",
    },
    RadarSite {
        id: "KILN",
        name: "Cincinnati",
        lat: 39.4203,
        lon: -83.8217,
        state: "OH",
    },
    RadarSite {
        id: "KILX",
        name: "Lincoln",
        lat: 40.1506,
        lon: -89.3369,
        state: "IL",
    },
    RadarSite {
        id: "KIND",
        name: "Indianapolis",
        lat: 39.7075,
        lon: -86.2803,
        state: "IN",
    },
    RadarSite {
        id: "KINX",
        name: "Tulsa",
        lat: 36.175,
        lon: -95.5644,
        state: "OK",
    },
    RadarSite {
        id: "KIWA",
        name: "Phoenix",
        lat: 33.2892,
        lon: -111.67,
        state: "AZ",
    },
    RadarSite {
        id: "KIWX",
        name: "N Indiana",
        lat: 41.3586,
        lon: -85.7,
        state: "IN",
    },
    RadarSite {
        id: "KJAX",
        name: "Jacksonville",
        lat: 30.4847,
        lon: -81.7019,
        state: "FL",
    },
    RadarSite {
        id: "KJGX",
        name: "Robins AFB",
        lat: 32.675,
        lon: -83.3511,
        state: "GA",
    },
    RadarSite {
        id: "KJKL",
        name: "Jackson",
        lat: 37.5908,
        lon: -83.3131,
        state: "KY",
    },
    RadarSite {
        id: "KLBB",
        name: "Lubbock",
        lat: 33.6542,
        lon: -101.814,
        state: "TX",
    },
    RadarSite {
        id: "KLCH",
        name: "Lake Charles",
        lat: 30.125,
        lon: -93.2158,
        state: "LA",
    },
    RadarSite {
        id: "KLIX",
        name: "New Orleans",
        lat: 30.3367,
        lon: -89.8256,
        state: "LA",
    },
    RadarSite {
        id: "KLNX",
        name: "North Platte",
        lat: 41.9578,
        lon: -100.576,
        state: "NE",
    },
    RadarSite {
        id: "KLOT",
        name: "Chicago",
        lat: 41.6044,
        lon: -88.0847,
        state: "IL",
    },
    RadarSite {
        id: "KLRX",
        name: "Elko",
        lat: 40.7397,
        lon: -116.803,
        state: "NV",
    },
    RadarSite {
        id: "KLSX",
        name: "St. Louis",
        lat: 38.6986,
        lon: -90.6828,
        state: "MO",
    },
    RadarSite {
        id: "KLTX",
        name: "Wilmington",
        lat: 33.9892,
        lon: -78.4292,
        state: "NC",
    },
    RadarSite {
        id: "KLVX",
        name: "Louisville",
        lat: 37.975,
        lon: -85.9436,
        state: "KY",
    },
    RadarSite {
        id: "KLWX",
        name: "Sterling",
        lat: 38.9753,
        lon: -77.4778,
        state: "VA",
    },
    RadarSite {
        id: "KLZK",
        name: "Little Rock",
        lat: 34.8364,
        lon: -92.2622,
        state: "AR",
    },
    RadarSite {
        id: "KMAF",
        name: "Midland/Odessa",
        lat: 31.9433,
        lon: -102.189,
        state: "TX",
    },
    RadarSite {
        id: "KMAX",
        name: "Medford",
        lat: 42.0811,
        lon: -122.717,
        state: "OR",
    },
    RadarSite {
        id: "KMBX",
        name: "Minot AFB",
        lat: 48.3925,
        lon: -100.864,
        state: "ND",
    },
    RadarSite {
        id: "KMHX",
        name: "Morehead City",
        lat: 34.7761,
        lon: -76.8761,
        state: "NC",
    },
    RadarSite {
        id: "KMKX",
        name: "Milwaukee",
        lat: 42.9678,
        lon: -88.5506,
        state: "WI",
    },
    RadarSite {
        id: "KMLB",
        name: "Melbourne",
        lat: 28.1133,
        lon: -80.6542,
        state: "FL",
    },
    RadarSite {
        id: "KMOB",
        name: "Mobile",
        lat: 30.6794,
        lon: -88.2397,
        state: "AL",
    },
    RadarSite {
        id: "KMPX",
        name: "Minneapolis",
        lat: 44.8489,
        lon: -93.5653,
        state: "MN",
    },
    RadarSite {
        id: "KMQT",
        name: "Marquette",
        lat: 46.5311,
        lon: -87.5486,
        state: "MI",
    },
    RadarSite {
        id: "KMRX",
        name: "Knoxville",
        lat: 36.1686,
        lon: -83.4017,
        state: "TN",
    },
    RadarSite {
        id: "KMSX",
        name: "Missoula",
        lat: 47.0411,
        lon: -113.986,
        state: "MT",
    },
    RadarSite {
        id: "KMTX",
        name: "Salt Lake City",
        lat: 41.2628,
        lon: -112.448,
        state: "UT",
    },
    RadarSite {
        id: "KMUX",
        name: "San Francisco",
        lat: 37.1553,
        lon: -121.898,
        state: "CA",
    },
    RadarSite {
        id: "KMVX",
        name: "Fargo",
        lat: 47.5278,
        lon: -97.325,
        state: "ND",
    },
    RadarSite {
        id: "KNKX",
        name: "San Diego",
        lat: 32.9189,
        lon: -117.042,
        state: "CA",
    },
    RadarSite {
        id: "KNQA",
        name: "Memphis",
        lat: 35.3447,
        lon: -89.8733,
        state: "TN",
    },
    RadarSite {
        id: "KOAX",
        name: "Omaha",
        lat: 41.3203,
        lon: -96.3669,
        state: "NE",
    },
    RadarSite {
        id: "KOHX",
        name: "Nashville",
        lat: 36.2472,
        lon: -86.5625,
        state: "TN",
    },
    RadarSite {
        id: "KOKX",
        name: "New York City",
        lat: 40.8656,
        lon: -72.8639,
        state: "NY",
    },
    RadarSite {
        id: "KOTX",
        name: "Spokane",
        lat: 47.6806,
        lon: -117.627,
        state: "WA",
    },
    RadarSite {
        id: "KPAH",
        name: "Paducah",
        lat: 37.0683,
        lon: -88.7719,
        state: "KY",
    },
    RadarSite {
        id: "KPBZ",
        name: "Pittsburgh",
        lat: 40.5317,
        lon: -80.0178,
        state: "PA",
    },
    RadarSite {
        id: "KPDT",
        name: "Pendleton",
        lat: 45.6906,
        lon: -118.853,
        state: "OR",
    },
    RadarSite {
        id: "KPOE",
        name: "Fort Polk",
        lat: 31.1556,
        lon: -92.9758,
        state: "LA",
    },
    RadarSite {
        id: "KPUX",
        name: "Pueblo",
        lat: 38.4594,
        lon: -104.181,
        state: "CO",
    },
    RadarSite {
        id: "KRAX",
        name: "Raleigh",
        lat: 35.6653,
        lon: -78.49,
        state: "NC",
    },
    RadarSite {
        id: "KRGX",
        name: "Reno",
        lat: 39.7542,
        lon: -119.462,
        state: "NV",
    },
    RadarSite {
        id: "KRIW",
        name: "Riverton",
        lat: 43.0661,
        lon: -108.477,
        state: "WY",
    },
    RadarSite {
        id: "KRLX",
        name: "Charleston",
        lat: 38.3111,
        lon: -81.7228,
        state: "WV",
    },
    RadarSite {
        id: "KRTX",
        name: "Portland",
        lat: 45.715,
        lon: -122.965,
        state: "OR",
    },
    RadarSite {
        id: "KSFX",
        name: "Pocatello",
        lat: 43.1058,
        lon: -112.686,
        state: "ID",
    },
    RadarSite {
        id: "KSGF",
        name: "Springfield",
        lat: 37.235,
        lon: -93.4006,
        state: "MO",
    },
    RadarSite {
        id: "KSHV",
        name: "Shreveport",
        lat: 32.4508,
        lon: -93.8414,
        state: "LA",
    },
    RadarSite {
        id: "KSJT",
        name: "San Angelo",
        lat: 31.3711,
        lon: -100.493,
        state: "TX",
    },
    RadarSite {
        id: "KSOX",
        name: "Santa Ana Mtns",
        lat: 33.8178,
        lon: -117.636,
        state: "CA",
    },
    RadarSite {
        id: "KSRX",
        name: "Fort Smith",
        lat: 35.2906,
        lon: -94.3619,
        state: "AR",
    },
    RadarSite {
        id: "KTBW",
        name: "Tampa Bay",
        lat: 27.7056,
        lon: -82.4017,
        state: "FL",
    },
    RadarSite {
        id: "KTFX",
        name: "Great Falls",
        lat: 47.4597,
        lon: -111.385,
        state: "MT",
    },
    RadarSite {
        id: "KTLH",
        name: "Tallahassee",
        lat: 30.3975,
        lon: -84.3289,
        state: "FL",
    },
    RadarSite {
        id: "KTLX",
        name: "Oklahoma City",
        lat: 35.3331,
        lon: -97.2778,
        state: "OK",
    },
    RadarSite {
        id: "KTWX",
        name: "Topeka",
        lat: 38.9969,
        lon: -96.2325,
        state: "KS",
    },
    RadarSite {
        id: "KTYX",
        name: "Montague",
        lat: 43.7556,
        lon: -75.68,
        state: "NY",
    },
    RadarSite {
        id: "KUDX",
        name: "Rapid City",
        lat: 44.125,
        lon: -102.83,
        state: "SD",
    },
    RadarSite {
        id: "KUEX",
        name: "Hastings",
        lat: 40.3208,
        lon: -98.4419,
        state: "NE",
    },
    RadarSite {
        id: "KVAX",
        name: "Moody AFB",
        lat: 30.8903,
        lon: -83.0019,
        state: "GA",
    },
    RadarSite {
        id: "KVBX",
        name: "Vandenberg AFB",
        lat: 34.8383,
        lon: -120.398,
        state: "CA",
    },
    RadarSite {
        id: "KVNX",
        name: "Vance AFB",
        lat: 36.7408,
        lon: -98.1275,
        state: "OK",
    },
    RadarSite {
        id: "KVTX",
        name: "Los Angeles",
        lat: 34.4117,
        lon: -119.179,
        state: "CA",
    },
    RadarSite {
        id: "KVWX",
        name: "Evansville",
        lat: 38.2603,
        lon: -87.7247,
        state: "IN",
    },
    RadarSite {
        id: "KYUX",
        name: "Yuma",
        lat: 32.4953,
        lon: -114.657,
        state: "AZ",
    },
    // Additional CONUS sites
    RadarSite {
        id: "KCRI",
        name: "Norman",
        lat: 35.2383,
        lon: -97.4602,
        state: "OK",
    },
    RadarSite {
        id: "KLGX",
        name: "Langley Hill",
        lat: 47.1169,
        lon: -124.1069,
        state: "WA",
    },
    RadarSite {
        id: "KMXX",
        name: "E Alabama",
        lat: 32.5367,
        lon: -85.7897,
        state: "AL",
    },
    // Non-CONUS / Territory sites
    RadarSite {
        id: "PACG",
        name: "Juneau",
        lat: 56.8527,
        lon: -135.529,
        state: "AK",
    },
    RadarSite {
        id: "PAEC",
        name: "Nome",
        lat: 64.5114,
        lon: -165.295,
        state: "AK",
    },
    RadarSite {
        id: "PAHG",
        name: "Anchorage",
        lat: 60.7258,
        lon: -151.351,
        state: "AK",
    },
    RadarSite {
        id: "PAIH",
        name: "Middleton Island",
        lat: 59.4614,
        lon: -146.303,
        state: "AK",
    },
    RadarSite {
        id: "PAKC",
        name: "King Salmon",
        lat: 58.6794,
        lon: -156.629,
        state: "AK",
    },
    RadarSite {
        id: "PAPD",
        name: "Fairbanks",
        lat: 65.0356,
        lon: -147.502,
        state: "AK",
    },
    RadarSite {
        id: "PHKI",
        name: "South Kauai",
        lat: 21.8942,
        lon: -159.552,
        state: "HI",
    },
    RadarSite {
        id: "PHKM",
        name: "Kohala",
        lat: 20.1253,
        lon: -155.778,
        state: "HI",
    },
    RadarSite {
        id: "PHMO",
        name: "Molokai",
        lat: 21.1328,
        lon: -157.18,
        state: "HI",
    },
    RadarSite {
        id: "PHWA",
        name: "South Shore",
        lat: 19.095,
        lon: -155.569,
        state: "HI",
    },
    RadarSite {
        id: "PGUA",
        name: "Andersen AFB",
        lat: 13.455,
        lon: 144.8111,
        state: "GU",
    },
    RadarSite {
        id: "TJUA",
        name: "San Juan",
        lat: 18.1156,
        lon: -66.0783,
        state: "PR",
    },
    RadarSite {
        id: "RODN",
        name: "Kadena",
        lat: 26.3019,
        lon: 127.9094,
        state: "OK",
    },
];

pub fn find_site(id: &str) -> Option<&'static RadarSite> {
    let id_upper = id.to_uppercase();
    RADAR_SITES.iter().find(|s| s.id == id_upper)
}

pub fn find_nearest_site(lat: f64, lon: f64) -> Option<&'static RadarSite> {
    RADAR_SITES.iter().min_by(|a, b| {
        let dist_a = (a.lat - lat).powi(2) + (a.lon - lon).powi(2);
        let dist_b = (b.lat - lat).powi(2) + (b.lon - lon).powi(2);
        dist_a
            .partial_cmp(&dist_b)
            .unwrap_or(std::cmp::Ordering::Equal)
    })
}

/// Great-circle distance in kilometers using the haversine formula.
pub fn haversine_km(lat1: f64, lon1: f64, lat2: f64, lon2: f64) -> f64 {
    const R: f64 = 6371.0; // Earth radius in km
    let d_lat = (lat2 - lat1).to_radians();
    let d_lon = (lon2 - lon1).to_radians();
    let lat1_r = lat1.to_radians();
    let lat2_r = lat2.to_radians();
    let a = (d_lat / 2.0).sin().powi(2) + lat1_r.cos() * lat2_r.cos() * (d_lon / 2.0).sin().powi(2);
    let c = 2.0 * a.sqrt().asin();
    R * c
}

/// Returns the `n` closest radar sites to the given lat/lon, sorted by distance.
pub fn find_nearest_sites(lat: f64, lon: f64, n: usize) -> Vec<&'static RadarSite> {
    let mut sites_with_dist: Vec<(&'static RadarSite, f64)> = RADAR_SITES
        .iter()
        .map(|s| (s, haversine_km(lat, lon, s.lat, s.lon)))
        .collect();
    sites_with_dist.sort_by(|a, b| a.1.partial_cmp(&b.1).unwrap_or(std::cmp::Ordering::Equal));
    sites_with_dist
        .into_iter()
        .take(n)
        .map(|(s, _)| s)
        .collect()
}

/// Returns all station IDs from the RADAR_SITES table.
pub fn all_site_ids() -> Vec<&'static str> {
    RADAR_SITES.iter().map(|s| s.id).collect()
}
